# Generated by Django 5.2 on 2025-05-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTrack', '0003_alter_notification_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='owner_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
