# Generated by Django 5.2 on 2025-05-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTrack', '0005_user_password_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='owner_department',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='owner_first_name',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='owner_last_name',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='owners',
            field=models.ManyToManyField(related_name='subscriptions', to='LicenseTrack.owner'),
        ),
    ]
